name: event_creation
dependencies:
- cairo=1.12.18=6
- cycler=0.10.0=py27_0
- dbus=1.10.10=0
- expat=2.1.0=0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- glib=2.43.0=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=1
- hdf5=1.8.17=1
- icu=54.1=0
- jpeg=8d=2
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.22=0
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=1.5.3=np111py27_0
- mkl=2017.0.1=0
- nose=1.3.7=py27_1
- numexpr=2.6.1=np111py27_2
- numpy=1.11.3=py27_0
- openssl=1.0.2j=0
- pandas=0.19.0=np111py27_0
- pango=1.39.0=1
- pcre=8.39=0
- pip=9.0.1=py27_1
- pixman=0.32.6=0
- pycairo=1.10.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=4.11.4=py27_4
- pytables=3.3.0=np111py27_0
- python=2.7.13=0
- python-dateutil=2.5.3=py27_0
- pytz=2016.7=py27_0
- pyyaml=3.12=py27_0
- qt=4.8.7=4
- readline=6.2=2
- scipy=0.18.1=np111py27_0
- setuptools=27.2.0=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- swig=3.0.10=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- xarray=0.8.2=py27_0
- yaml=0.1.6=0
- zlib=1.2.8=3
- pip:
  - ptsa==1.0.3
  - pyedflib==0.1.6
  - pywavelets==0.5.1
  - tables==3.3.0

