
paths : &PATHS
  rhino_root     : &RHINO '/'
  data_root      : !join [*RHINO, 'data/eeg']
  loc_db_root    : !join [*RHINO, 'home2', 'RAM_maint', 'stim']
  db_root        : *RHINO
  events_root    : !join [*RHINO, 'data/events']
  freesurfer_bin : !join [*RHINO, 'usr/global/freesurfer/bin']

inputs: &INPUTS
  protocol :
  subject :
  code :
  montage :
  localization :
  experiment :
  original_experiment :
  session :
  original_session :
  PS4 :


options:
  - dest: log_debug
    arg: debug
    help: 'Prints debug information to terminal during execution'
  - dest: montage_only
    arg: montage-only
    help: 'Imports a montage instead of importing events'
  - dest: localization_only
    arg: localization-only
    help: 'Adds localization information to database instead of importing events'
  - dest: change_experiment
    arg: change-experiment
    help: 'Signals that the name of the experiment changes on import. Defaults to true for PS* behavioral'
  - dest: change_session
    arg: change-session
    help: 'Signals that the session number changes on import'
  - dest: allow_convert
    arg: allow-convert
    help: 'Attempt to convert events from matlab if standard events creation fails'
  - dest: force_convert
    arg: force-convert
    help: 'ONLY attempt conversion of events from matlab and skips standard import'
  - dest: force_events
    arg: force-events
    help: 'Forces events creation even if no changes have occurred'
  - dest: force_eeg
    arg: force-eeg
    help: 'Forces eeg splitting even if no changes have occurred'
  - dest: force_montage
    arg: force-montage
    help: 'Forces montage change even if no changes have occurred'
  - dest: force_localization
    arg: force-localization
    help: 'Forces localization import even if no changes have occurred'
  - dest: force_dykstra
    arg:  force-dykstra
    help: 'When re-running localization import, also recompute Dykstra correction'
  - dest: clean_db
    arg: clean-only
    help: 'ONLY cleans the database. Removes empty folders and folders without processed equivalent'
  - dest: aggregate
    arg: aggregate-only
    help: 'ONLY aggreate index files. Run if any paths have been manually changed'
  - dest: do_compare
    arg: do-compare
    help: 'Compare created JSON events to MATLAB events and undo import if they do mot match'
  - dest: json_file
    arg: json
    action: store
    default: null
    help: 'Imports all sessions from specified JSON file. Build JSON file with option --build-db'
  - dest: db_name
    arg: build-db
    action: store
    default: null
    help: 'Builds a JSON database which can later be imported. Current options are "sharing" or "ram"'
  - dest: view_only
    arg: view-only
    help: 'View information about already-submitted subjects'
  - dest: wav_only
    arg: wav-only
    help: 'Only import .wav files.'
  - dest: show_plots
    arg: show-plots
    help: 'Show plots of fit and residuals when aligning data (not available when running with sudo)'
  - dest: inputs
    arg: set-input
    action: append
    help: 'Set inputs for subsequent submission (KEY=VALUE). Will not prompt for these inputs if provided.'
    options: *INPUTS
  - dest: paths
    arg: path
    action: append
    help: 'Override the path set in configuration file (KEY=VALUE).'
    options: *PATHS
